name: Generate SDK

on:
  push:
    paths:
      - "cmd/api/**/*.go"
      - "internal/modules/**/dto/*.go"
      - "VERSION"
    branches:
      - main

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:
  generate-sdk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read version
        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Install swag
        run: go install github.com/swaggo/swag/cmd/swag@latest

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Install bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Generate swagger
        run: make swag-gen

      - name: Install SDK dependencies
        run: cd sdk && bun install

      - name: Generate SDK
        run: cd sdk && bun run convert

      - name: Update package.json version
        run: |
          cd sdk
          sed -i "s/\"version\": \".*\"/\"version\": \"$VERSION\"/" package.json

      - name: Upload SDK artifact
        uses: actions/upload-artifact@v4
        with:
          name: sdk
          path: sdk/
          retention-days: 30

      - name: Commit SDK changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add sdk/
          git commit -m "chore: update SDK to ${{ env.VERSION }}" || echo "No changes to commit"

      - name: Push changes
        run: git push

      - name: Publish to GitHub Packages
        working-directory: ./sdk
        run: |
          # 1. Create the .npmrc with the scope mapping
          echo "@ambrizals:registry=https://npm.pkg.github.com" > .npmrc
          echo "//npm.pkg.github.com/:_authToken=${BUN_AUTH_TOKEN}" >> .npmrc

          # 2. Run publish
          bun publish
        env:
          BUN_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
